name: Create Release Build
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 1.1.0)'
        required: true
      versionCode:
        description: 'Version number (10100)'
        required: true
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:       
    - name: build
      run: echo "Building the code..."
    - name: version
      run: echo ""${{ github.event.inputs.versionName }}""
      id: version
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        #body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
